"""Create initial tables

Revision ID: 0db59e8fe555
Revises: 
Create Date: 2026-02-07 19:31:41.642722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db59e8fe555'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_role', sa.String(length=255), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('clock_code', sa.String(length=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("clock_code ~ '^[0-9]{4}$'", name='check_clock_code_format'),
    sa.CheckConstraint('daily_rate >= 0', name='check_daily_rate_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_clock_code', 'employees', ['clock_code'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_employee_created', 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('IN', 'OUT')", name='check_time_entry_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_timestamp', 'time_entries', ['employee_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('clock_in_id', sa.Integer(), nullable=False),
    sa.Column('clock_out_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('money_gained', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at > started_at', name='check_shift_times'),
    sa.CheckConstraint('money_gained >= 0', name='check_money_gained_positive'),
    sa.ForeignKeyConstraint(['clock_in_id'], ['time_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clock_out_id'], ['time_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clock_in_id'),
    sa.UniqueConstraint('clock_out_id')
    )
    op.create_index('idx_employee_started', 'shifts', ['employee_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index('idx_employee_started', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.drop_index('idx_employee_timestamp', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index('idx_employee_created', table_name='employees')
    op.drop_index('idx_active_clock_code', table_name='employees', postgresql_where=sa.text('is_active = true'))
    op.drop_table('employees')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
